# Generated by Django 4.1.13 on 2024-04-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(max_length=200)),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("url", models.URLField()),
            ],
        ),
    ]
